package org.r2d2c3p0.cr.generator.html;

import org.apache.log4j.Logger;

public class MainJSPage {

	private final static Logger logger = Logger.getLogger("CRGAppLogger");

	public static String print() {

		logger.debug(" [MainJSPage] called.");
		return "$(document).ready(function () {\n\n"
				+"	 var table = $('#crgenerator').DataTable({\n"
				+"         \"data\": crgenetordata.data,\n"
				+"         select:\"single\",\n"
				+"         \"columns\": [\n"
				+"             {\n"
				+"                 \"className\": 'details-control',\n"
				+"                 \"orderable\": false,\n"
				+"                 \"data\": null,\n"
				+"                 \"defaultContent\": '',\n"
				+"                 \"render\": function () {\n"
				+"                     return '<i class=\"fa fa-plus-square\" aria-hidden=\"true\"></i>';\n"
				+"                 },\n"
				+"                 width:\"15px\"\n"
				+"             },\n"
				+"             { \"data\": \"commonname\" },\n"
				+"             { \"data\": \"sstatus\" },\n"
				+"             { \"data\": \"aserialnumber\" }\n"
				+"             \n"
				+"         ],\n"
				+"         \"order\": [[1, 'asc']]\n"
				+"     });\n"
				+"\n"
				+"     // Add event listener for opening and closing details\n"
				+"     $('#crgenerator tbody').on('click', 'td.details-control', function () {\n"
				+"         var tr = $(this).closest('tr');\n"
				+"         var tdi = tr.find('i.fa');\n"
				+"         var row = table.row(tr);\n"
				+"\n"
				+"         if (row.child.isShown()) {\n"
				+"             // This row is already open - close it\n"
				+"             row.child.hide();\n"
				+"             tr.removeClass('shown');\n"
				+"             tdi.first().removeClass('fa-minus-square');\n"
				+"             tdi.first().addClass('fa-plus-square');\n"
				+"         }\n"
				+"         else {\n"
				+"             // Open this row\n"
				+"             row.child(format(row.data())).show();\n"
				+"             tr.addClass('shown');\n"
				+"             tdi.first().removeClass('fa-plus-square');\n"
				+"             tdi.first().addClass('fa-minus-square');\n"
				+"         }\n"
				+"     });\n"
				+"\n"
				+"     table.on(\"user-select\", function (e, dt, type, cell, originalEvent) {\n"
				+"         if ($(cell.node()).hasClass(\"details-control\")) {\n"
				+"             e.preventDefault();\n"
				+"         }\n"
				+"     });\n"
				+"});\n"
				+"\n"
				+"function format(d){\n"
				+"    \n"
				+"     // `d` is the original data object for the row\n"
				+"     return '<table id=\"crgtable\" cellpadding=\"5\" cellspacing=\"0\" border=\"0\" style=\"padding-left:50px;\">' +\n"
				+"         '<tr>' +\n"
				+"             '<td>Key type:</td>' +\n"
				+"             '<td>' + d.pkey + '</td>' +\n"
				+"         '</tr>' +\n"
				+"         '<tr>' +\n"
				+"             '<td>Alias:</td>' +\n"
				+"             '<td>' + d.alias + '</td>' +\n"
				+"         '</tr>' +\n"
				+"         '<tr>' +\n"
				+"             '<td>Expires on:</td>' +\n"
				+"             '<td>' + d.expires + '</td>' +\n"
				+"         '</tr>' +\n"
				+"		 '<tr>' +\n"
				+"             '<td>Issued on:</td>' +\n"
				+"             '<td> ' + d.issued + ' </td>' +\n"
				+"         '</tr>' +\n"
				+"		 '<tr>' +\n"
				+"             '<td>Issued by:</td>' +\n"
				+"             '<td> ' + d.issuer + ' </td>' +\n"
				+"         '</tr>' +\n"
				+"         '<tr>' +\n"
				+"             '<td>Keystore:</td>' +\n"
				+"             '<td> ' + d.keystore + ' </td>' +\n"
				+"         '</tr>' +\n"
				+"         '<tr>' +\n"
				+"             '<td>Chained Certificates:</td>' +\n"
				+"             '<td>' + d.chain + '</td>' +\n"
				+"         '</tr>' +\n"
				+"		'<tr>' +\n"
				+"             '<td>SAN Entries:</td>' +\n"
				+"             '<td>' + d.san + '</td>' +\n"
				+"         '</tr>' +\n"
				+"		'<tr>' +\n"
				+"             '<td>Signature Algorithm:</td>' +\n"
				+"             '<td>' + d.sigal + '</td>' +\n"
				+"         '</tr>' +\n"
				+"             '<td>Serial Number(Decimal):</td>' +\n"
				+"             '<td>' + d.serialnumber + '</td>' +\n"
				+"         '</tr>' +\n"
				+"     '</table>';  \n"
				+"}\n"
				+"\n"
				+"var crgenetordata = {\n"
				+"  \"data\": [\n";

	}

}